package protocol

// outboundProtobufVersion is the first server version at which an outbound
// classic message ID is replaced by ID+200 with a protobuf body. Staged
// migrations through historical data are collapsed to the supported floor;
// later gates mirror GetServerVersionForMessage in API 10.48.01 EClient.h.
var outboundProtobufVersion = map[int]int{
	OutReqExecutions:               SupportedMinServerVersion,
	OutPlaceOrder:                  SupportedMinServerVersion,
	OutCancelOrder:                 SupportedMinServerVersion,
	OutReqGlobalCancel:             SupportedMinServerVersion,
	OutReqOpenOrders:               SupportedMinServerVersion,
	OutReqAutoOpenOrders:           SupportedMinServerVersion,
	OutReqAllOpenOrders:            SupportedMinServerVersion,
	OutReqCompletedOrders:          SupportedMinServerVersion,
	OutReqContractData:             SupportedMinServerVersion,
	OutReqMktData:                  SupportedMinServerVersion,
	OutCancelMktData:               SupportedMinServerVersion,
	OutReqMktDepth:                 SupportedMinServerVersion,
	OutCancelMktDepth:              SupportedMinServerVersion,
	OutReqMarketDataType:           SupportedMinServerVersion,
	OutReqAccountUpdates:           SupportedMinServerVersion,
	OutReqManagedAccounts:          SupportedMinServerVersion,
	OutReqPositions:                SupportedMinServerVersion,
	OutCancelPositions:             SupportedMinServerVersion,
	OutReqAccountSummary:           SupportedMinServerVersion,
	OutCancelAccountSummary:        SupportedMinServerVersion,
	OutReqPositionsMulti:           SupportedMinServerVersion,
	OutCancelPositionsMulti:        SupportedMinServerVersion,
	OutReqAccountUpdatesMulti:      SupportedMinServerVersion,
	OutCancelAccountUpdatesMulti:   SupportedMinServerVersion,
	OutReqHistoricalData:           MinServerVersionProtobufHistoricalData,
	OutCancelHistoricalData:        MinServerVersionProtobufHistoricalData,
	OutReqRealTimeBars:             MinServerVersionProtobufHistoricalData,
	OutCancelRealTimeBars:          MinServerVersionProtobufHistoricalData,
	OutReqHeadTimestamp:            MinServerVersionProtobufHistoricalData,
	OutCancelHeadTimestamp:         MinServerVersionProtobufHistoricalData,
	OutReqHistogramData:            MinServerVersionProtobufHistoricalData,
	OutCancelHistogramData:         MinServerVersionProtobufHistoricalData,
	OutReqHistoricalTicks:          MinServerVersionProtobufHistoricalData,
	OutReqTickByTickData:           MinServerVersionProtobufHistoricalData,
	OutCancelTickByTickData:        MinServerVersionProtobufHistoricalData,
	OutReqNewsBulletins:            MinServerVersionProtobufNewsData,
	OutCancelNewsBulletins:         MinServerVersionProtobufNewsData,
	OutReqNewsArticle:              MinServerVersionProtobufNewsData,
	OutReqNewsProviders:            MinServerVersionProtobufNewsData,
	OutReqHistoricalNews:           MinServerVersionProtobufNewsData,
	OutReqWSHMetaData:              MinServerVersionProtobufNewsData,
	OutCancelWSHMetaData:           MinServerVersionProtobufNewsData,
	OutReqWSHEventData:             MinServerVersionProtobufNewsData,
	OutCancelWSHEventData:          MinServerVersionProtobufNewsData,
	OutReqScannerParameters:        MinServerVersionProtobufScanData,
	OutReqScannerSubscription:      MinServerVersionProtobufScanData,
	OutCancelScannerSubscription:   MinServerVersionProtobufScanData,
	OutReqPnL:                      MinServerVersionProtobufScanData,
	OutCancelPnL:                   MinServerVersionProtobufScanData,
	OutReqPnLSingle:                MinServerVersionProtobufScanData,
	OutCancelPnLSingle:             MinServerVersionProtobufScanData,
	OutRequestFA:                   MinServerVersionProtobufRestMessages1,
	OutExerciseOptions:             MinServerVersionProtobufRestMessages1,
	OutReqCalcImpliedVolatility:    MinServerVersionProtobufRestMessages1,
	OutCancelCalcImpliedVolatility: MinServerVersionProtobufRestMessages1,
	OutReqCalcOptionPrice:          MinServerVersionProtobufRestMessages1,
	OutCancelCalcOptionPrice:       MinServerVersionProtobufRestMessages1,
	OutReqSecDefOptParams:          MinServerVersionProtobufRestMessages2,
	OutReqSoftDollarTiers:          MinServerVersionProtobufRestMessages2,
	OutReqFamilyCodes:              MinServerVersionProtobufRestMessages2,
	OutReqMatchingSymbols:          MinServerVersionProtobufRestMessages2,
	OutReqSmartComponents:          MinServerVersionProtobufRestMessages2,
	OutReqMarketRule:               MinServerVersionProtobufRestMessages2,
	OutReqUserInfo:                 MinServerVersionProtobufRestMessages2,
	OutReqIds:                      MinServerVersionProtobufRestMessages3,
	OutReqCurrentTime:              MinServerVersionProtobufRestMessages3,
	OutReqCurrentTimeInMillis:      MinServerVersionProtobufRestMessages3,
	OutStartAPI:                    MinServerVersionProtobufRestMessages3,
	OutQueryDisplayGroups:          MinServerVersionProtobufRestMessages3,
	OutSubscribeToGroupEvents:      MinServerVersionProtobufRestMessages3,
	OutUpdateDisplayGroup:          MinServerVersionProtobufRestMessages3,
	OutUnsubscribeFromGroupEvents:  MinServerVersionProtobufRestMessages3,
	OutReqMktDepthExchanges:        MinServerVersionProtobufRestMessages3,
	OutCancelContractData:          MinServerVersionBrokerSideOneShotCancel,
	OutCancelHistoricalTicks:       MinServerVersionBrokerSideOneShotCancel,
	OutReqConfig:                   MinServerVersionConfig,
}

// OutboundProtobufVersion reports the first negotiated server version that
// requires a protobuf body for the outbound base message ID.
func OutboundProtobufVersion(msgID int) (int, bool) {
	version, ok := outboundProtobufVersion[msgID]
	return version, ok
}
